# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0011_auto_20170404_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuron',
            name='typ',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
