# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0012_neuron_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('request', models.CharField(max_length=600)),
                ('time', models.DateTimeField()),
                ('response', models.CharField(max_length=600)),
                ('responsestatus', models.IntegerField()),
                ('token', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='e',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='correct',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
