# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0014_auto_20170415_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='method',
            field=models.CharField(default='GET', max_length=100),
            preserve_default=False,
        ),
    ]
