# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0016_auto_20170420_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuron',
            name='calculateddifficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='calculateddifficulty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
