# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0017_auto_20170420_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='linkability1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='linkability2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='linkability3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='linkability4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='linkability5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='linkability6',
            field=models.FloatField(default=0),
        ),
    ]
