# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0019_auto_20170423_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Question')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users')),
            ],
        ),
    ]
