# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0020_questionsuggestion_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('right', models.IntegerField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Question')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('right', models.IntegerField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Question')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('right', models.IntegerField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Question')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users')),
            ],
        ),
    ]
