# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0021_hardness_prefer_useful'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Question')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users')),
            ],
        ),
        migrations.AddField(
            model_name='userquestion',
            name='righte',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
