# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='linkneuron',
            field=models.ManyToManyField(to='mathematics.Neuron'),
        ),
        migrations.AddField(
            model_name='question',
            name='rightproblems',
            field=models.ManyToManyField(blank=True, related_name='_question_rightproblems_+', to='mathematics.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='twinproblems',
            field=models.ManyToManyField(blank=True, related_name='_question_twinproblems_+', to='mathematics.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='wrongproblems',
            field=models.ManyToManyField(blank=True, related_name='_question_wrongproblems_+', to='mathematics.Question'),
        ),
    ]
