# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0002_auto_20170315_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='linkneuron',
            field=models.ManyToManyField(blank=True, to='mathematics.Neuron'),
        ),
    ]
