# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0003_auto_20170315_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.IntegerField(choices=[(1, 'Expl'), (2, 'Exer'), (3, 'Prob'), (4, 'DIY'), (5, 'Qui')]),
        ),
    ]
