# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0007_auto_20170324_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNeuron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('e', models.IntegerField()),
                ('answer', models.CharField(max_length=100)),
                ('right', models.CharField(max_length=100)),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=100)),
                ('login', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userquestion',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users'),
        ),
        migrations.AddField(
            model_name='users',
            name='neuron',
            field=models.ManyToManyField(through='mathematics.UserNeuron', to='mathematics.Neuron'),
        ),
        migrations.AddField(
            model_name='users',
            name='question',
            field=models.ManyToManyField(through='mathematics.UserQuestion', to='mathematics.Question'),
        ),
        
        migrations.AddField(
            model_name='userneuron',
            name='neuronid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Neuron'),
        ),
        migrations.AddField(
            model_name='userneuron',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.Users'),
        ),
        migrations.AddField(
            model_name='connect',
            name='begin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mathematics.Neuron'),
        ),
        migrations.AddField(
            model_name='connect',
            name='ending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mathematics.Neuron'),
        ),
        migrations.AddField(
            model_name='neuron',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mathematics.Chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuron',
            name='to',
            field=models.ManyToManyField(through='mathematics.Connect', to='mathematics.Neuron'),
        ),
        
    ]
