# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0008_auto_20170324_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
