# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0009_auto_20170325_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuron',
            name='bolder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neuron',
            name='fonts',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuron',
            name='names',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
